#!/usr/bin/env python3
"""Writes the implementations of `Format` and `FormatArgs` for tuples of 1 to `MAX_SIZE` elements
into `std_experimental.fix`, replacing the lines between `BEGIN_MARK` and `END_MARK`. Run it from
the directory it is in."""

MAX_SIZE = 12
SOURCE = "std_experimental.fix"
BEGIN_MARK = "// BEGIN tuple implementations generated by `gen_tuples.py`."
END_MARK = "// END tuple implementations generated by `gen_tuples.py`."


def tuple_impls():
    lines = []
    for size in range(1, MAX_SIZE + 1):
        close = ",)" if size == 1 else ")"
        constraints = ", ".join(f"t{i} : Format" for i in range(size))
        tuple_type = "(" + ", ".join(f"t{i}" for i in range(size)) + close
        pattern = "(" + ", ".join(f"x{i}" for i in range(size)) + close
        elements = '.write_text(", ")'.join(f".write_text(x{i})" for i in range(size))
        puts = "".join(f"._put_next(x{i})" for i in range(size))
        # `Format` writes the tuple like `ToString`: `(x0, x1)`, and `(x0,)` for one element.
        lines += [
            "",
            f"impl [{constraints}] {tuple_type} : Format {{",
            f'    write_text = |{pattern}, out| out.write_text("("){elements}.write_text("{close}");',
            "}",
            "",
            f"impl [{constraints}] {tuple_type} : FormatArgs {{",
            f"    write_args = |{pattern}, cursor| cursor{puts};",
            "}",
        ]
    return lines


def main():
    with open(SOURCE) as f:
        lines = f.read().split("\n")
    begin = lines.index(BEGIN_MARK)
    end = lines.index(END_MARK)
    lines[begin + 1 : end] = tuple_impls() + [""]
    with open(SOURCE, "w") as f:
        f.write("\n".join(lines))


main()
